# Generated by Django 4.0.4 on 2022-05-11 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_periferico',
            fields=[
                ('idTipo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Tipo')),
                ('nombreTipo', models.CharField(max_length=50, verbose_name='Nombre del Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Periferico',
            fields=[
                ('idperiferico', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Idperiferico')),
                ('marca', models.CharField(max_length=20, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Modelo')),
                ('nombre', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre')),
                ('precio', models.CharField(blank=True, max_length=20, null=True, verbose_name='Precio')),
                ('Tipo_periferico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventasgamer.tipo_periferico')),
            ],
        ),
    ]
