# Generated by Django 4.0.4 on 2022-07-07 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_consulta', models.IntegerField(choices=[[0, 'consulta'], [1, 'reclamo'], [2, 'sugerencia'], [3, 'felicitaciones']])),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_periferico',
            fields=[
                ('idTipo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Tipo')),
                ('nombreTipo', models.CharField(max_length=50, verbose_name='Nombre del Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=50, verbose_name='Correo')),
                ('contrasenna', models.CharField(max_length=50, verbose_name='Contraseña')),
                ('nombreUsuario', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Periferico',
            fields=[
                ('idperiferico', models.IntegerField(default='Some String', primary_key=True, serialize=False, verbose_name='Idperiferico')),
                ('marca', models.CharField(default='Some String', max_length=20, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Modelo')),
                ('nombre', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre')),
                ('precio', models.CharField(blank=True, max_length=20, null=True, verbose_name='Precio')),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
                ('tipo_periferico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventasgamer.tipo_periferico')),
            ],
        ),
    ]
