# Generated by Django 4.0.4 on 2022-07-07 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventasgamer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periferico',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
    ]
