# Generated by Django 4.0.4 on 2022-05-19 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventasgamer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periferico',
            old_name='Tipo_periferico',
            new_name='tipo_periferico',
        ),
    ]
