# Generated by Django 4.0.4 on 2022-07-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventasgamer', '0002_alter_periferico_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periferico',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
