# Generated by Django 4.0.4 on 2022-06-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventasgamer', '0002_rename_tipo_periferico_periferico_tipo_periferico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=50, verbose_name='Correo')),
                ('contrasenna', models.CharField(max_length=50, verbose_name='Contrasenna')),
            ],
        ),
        migrations.AlterField(
            model_name='periferico',
            name='idperiferico',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
