# Generated by Django 4.0.4 on 2022-06-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventasgamer', '0003_usuario_alter_periferico_idperiferico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contrasenna',
            field=models.CharField(blank=True, max_length=50, verbose_name='Contrasenna'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Correo'),
        ),
    ]
