# Generated by Django 4.0.4 on 2022-07-07 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventasgamer', '0003_alter_periferico_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periferico',
            name='idperiferico',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Idperiferico'),
        ),
        migrations.AlterField(
            model_name='periferico',
            name='marca',
            field=models.CharField(max_length=20, verbose_name='Marca'),
        ),
    ]
