# Generated by Django 4.0.4 on 2022-06-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventasgamer', '0005_alter_usuario_contrasenna_alter_usuario_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periferico',
            name='idperiferico',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Idperiferico'),
        ),
    ]
