# Generated by Django 4.0.4 on 2022-06-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventasgamer', '0009_remove_periferico_idperiferico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periferico',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='periferico',
            name='imagen',
        ),
        migrations.AddField(
            model_name='periferico',
            name='idperiferico',
            field=models.IntegerField(default='Some String', primary_key=True, serialize=False, verbose_name='Idperiferico'),
        ),
        migrations.AddField(
            model_name='periferico',
            name='marca',
            field=models.CharField(default='Some String', max_length=20, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='periferico',
            name='modelo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='periferico',
            name='nombre',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='periferico',
            name='precio',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Precio'),
        ),
    ]
